# runtime: python311
# entrypoint: gunicorn -b :$PORT app:app

# env_variables:
#   GOOGLE_CLOUD_PROJECT: "myprojectrag"

# handlers:
# - url: .*
#   script: auto


runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

